server:
  port: 8080
spring:
  application:
    name: test-application
  datasource:
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    default-schema: test
  data:
    redis:
      host: localhost
      port: 6379

